[commands]
  # The command prefix, that each command must start with
  prefix = "!"

  # Configuration for the Tag command
  [commands.tag]

    [commands.tag.modify]
      # A list with roles whose users are allowed to modify tags.
      allowed-roles= [  ]


[database]
  connection-url = "jdbc:sqlite:db.sqlite"

[messages]
  [messages.error]
    self-destruct = true
    destruction-delay = 5
  [messages.information]
    self-destruct = true
    destruction-delay = 5
  [messages.success]
    self-destruct = true
    destruction-delay = 5
  [messages.none]
    self-destruct = true
    destruction-delay = 5